### ISSUE TITLE
version.partition is a floating point number

### ISSUE THREAD

**Issue by clementfarabet** [bshillingford/python-torchfile#5]
Getting an error at this [line](https://github.com/bshillingford/python-torchfile/blob/master/torchfile.py#L364), when running:

```lua
torch.save('/tmp/test.t7', {hello=123, world=torch.rand(1,2,3)})
```

```python
o = torchfile.load('/tmp/test.t7')
ValueError: invalid literal for int() with base 10: b'1.0'
```

The version in my `test.t7` file is `"V 1.0"`. 

This is with Python 2.7 or 3.5, and Lua 5.3.

**Comment by clementfarabet** [comment]
Fixing [here](https://github.com/bshillingford/python-torchfile/pull/6).

**Comment by bshillingford** [comment]
Thank you!
